language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
#  - g++ main.cpp -std=c++17 -o raytracing
  - mkdir build
  - cmake -H. -Bbuild
  - cd build
  - make
  - ./build/raytracing
