os:
  - Visual Studio 2017

#platform:
#  - x64

configuration:
  - Debug
#  - Release # Removed due to duplication and longer time for completing the tests.

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake -DGTEST_LINKED_AS_SHARED_LIBRARY=1 ..
  - cmake -DGTEST_LINKED_AS_SHARED_LIBRARY=1 --build .

build:
  project: build\raytracing.sln
  parallel: true
  verbosity: normal

test_script:
  - ls ./*
  - dir *
  - ctest -V
  - cp .\resource\sample_texture.jpg .
  - .\bin\%CONFIGURATION%\raytracing.exe --samples=8 --width=4 --height=2
