os:
  - Visual Studio 2017

platform:
  - x64

configuration:
  - Debug
#  - Release # Removed due to duplication and longer time for completing the tests.

before_build:
  - cmake -H. -Bbuild -A%PLATFORM%

build:
  project: build\raytracing.sln
  parallel: true
  verbosity: normal

test_script:
  - cp .\resource\sample_texture.jpg .
  - .\bin\%CONFIGURATION%\raytracing.exe --samples=8 --width=4 --height=2
