os:
  - Visual Studio 2017

platform:
  - x64

configuration:
  - Debug
#  - Release # Removed due to duplication and longer time for completing the tests.

before_build:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

build:
  project: build\raytracing.sln
  parallel: true
  verbosity: normal

test_script:
  - ctest -V
  - cp .\resource\sample_texture.jpg .
  - .\bin\%CONFIGURATION%\raytracing.exe --samples=8 --width=4 --height=2
