os:
  - Visual Studio 2017

#platform:
#  - x64

configuration:
  - Debug
#  - Release # Removed due to duplication and longer time for completing the tests.

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake -Dgtest_force_shared_crt=TRUE ..
  - cmake --build .

build:
  project: build\raytracing.sln
  parallel: true
  verbosity: normal

test_script:
  - cd build
  - ctest -V -C Debug
  - cd ..
  - cp .\resource\sample_texture.jpg .
  - .\bin\%CONFIGURATION%\raytracing.exe --samples=8 --width=4 --height=2
