os:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - x64

configuration:
  - Debug
#  - Release # Removed due to duplication and longer time for completing the tests.

before_build:
  - cmake -H. -Bbuild -A%PLATFORM%

build:
  project: build\raytracing.sln
  parallel: true
  verbosity: normal

test_script:
  - .\bin\%CONFIGURATION%\raytracing.exe
