os:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmake -H. -Bbuild -A%PLATFORM%

build:
  project: build\raytracing.sln
  parallel: true
  verbosity: normal

test_script:
  - .\bin\%CONFIGURATION%\raytracing.exe
  #- .\build\%CONFIGURATION%\raytracing.exe
